const $ = (selector) => document.querySelector(selector);

export const sceneCanvas = $("#sceneCanvas");
export const scene = sceneCanvas.getContext("2d");
export const previewCanvas = $("#previewCanvas");
export const preview = previewCanvas.getContext("2d");
export const sideReferenceCanvas = $("#sideReferenceCanvas");
export const sideReferenceCtx = sideReferenceCanvas?.getContext("2d");

export const els = {
  startScreen: $("#startScreen"),
  startBeadButton: $("#startBeadButton"),
  startDrawButton: $("#startDrawButton"),
  drawingStudio: $("#drawingStudio"),
  drawingBackButton: $("#drawingBackButton"),
  drawSettingsButton: $("#drawSettingsButton"),
  drawResetButton: $("#drawResetButton"),
  drawCanvas: $("#drawCanvas"),
  drawSizeSelect: $("#drawSizeSelect"),
  drawResizeModal: $("#drawResizeModal"),
  drawResizeModalTitle: $("#drawResizeModalTitle"),
  drawResizeConfirmBtn: $("#drawResizeConfirmBtn"),
  drawResizeCancelBtn: $("#drawResizeCancelBtn"),
  drawResizeCloseBtn: $("#drawResizeCloseBtn"),
  drawAnchorGrid: $("#drawAnchorGrid"),
  drawCurrentColorSwatch: $("#drawCurrentColorSwatch"),
  drawCurrentColorCode: $("#drawCurrentColorCode"),
  drawClearButton: $("#drawClearButton"),
  drawImportButton: $("#drawImportButton"),
  drawExportButton: $("#drawExportButton"),
  drawShortCodeButton: $("#drawShortCodeButton"),
  drawUsePatternButton: $("#drawUsePatternButton"),
  drawCodeInput: $("#drawCodeInput"),
  drawPaletteMeta: $("#drawPaletteMeta"),
  drawRecentColors: $("#drawRecentColors"),
  drawPalette: $("#drawPalette"),
  beadBackButton: $("#beadBackButton"),
  statusLine: $("#statusLine"),
  patternMeta: $("#patternMeta"),
  patternList: $("#patternList"),
  customImageInput: $("#customImageInput"),
  customWhiteToggle: $("#customWhiteToggle"),
  customDenoiseSlider: $("#customDenoiseSlider"),
  customDenoiseValue: $("#customDenoiseValue"),
  patternSizeSlider: $("#patternSizeSlider"),
  patternSizeValue: $("#patternSizeValue"),

  customSizeMeta: $("#customSizeMeta"),
  customStats: $("#customStats"),
  patternColorStats: $("#patternColorStats"),
  targetCount: $("#targetCount"),
  controlTitle: $("#controlTitle"),
  toolMeta: $("#toolMeta"),
  stageControls: $("#stageControls"),
  sideReference: $("#sideReference"),
  sideReferenceMeta: $("#sideReferenceMeta"),
  sideReferenceLegend: $("#sideReferenceLegend"),
  studioGrid: $("#studioGrid"),
  workflowProgress: $("#workflowProgress"),
  currentPatternChip: $("#currentPatternChip"),
  currentPatternThumb: document.querySelector("#currentPatternChip .current-pattern-thumb"),
  currentPatternName: $("#currentPatternName"),
  currentPatternMeta: $("#currentPatternMeta"),
  collectionButton: $("#collectionButton"),
  collectionModal: $("#collectionModal"),
  collectionModalClose: $("#collectionModalClose"),
  settingsButton: $("#settingsButton"),
  settingsDot: $("#settingsDot"),
  settingsModal: $("#settingsModal"),
  settingsModalClose: $("#settingsModalClose"),
  shareModal: $("#shareModal"),
  shareModalClose: $("#shareModalClose"),
  remapModal: $("#remapModal"),
  remapModalTitle: $("#remapModalTitle"),
  remapModalBody: $("#remapModalBody"),
  remapModalClose: $("#remapModalClose"),
  remapDoneButton: $("#remapDoneButton"),
  remapResetButton: $("#remapResetButton"),
  toolRack: $("#toolRack"),
  rightPanelTitle: $("#rightPanelTitle"),
  colorPalette: $("#colorPalette"),
  colorMeta: $("#colorMeta"),
  sharePanel: $("#sharePanel"),
  collectionPanel: $("#collectionPanel"),
  collectionCount: $("#collectionCount"),
  bgThemeSelect: $("#bgThemeSelect"),
  topToolStyleSelect: $("#topToolStyleSelect"),
  sandboxButton: $("#sandboxButton"),
  chooseStartButton: $("#chooseStartButton"),
  resetButton: $("#resetButton"),
  toast: $("#toast"),
  placeHint: $("#placeHint"),
  achievementToast: $("#achievementToast"),
};
