const $ = (selector) => document.querySelector(selector);

export const sceneCanvas = $("#sceneCanvas");
export const scene = sceneCanvas.getContext("2d");
export const previewCanvas = $("#previewCanvas");
export const preview = previewCanvas.getContext("2d");
export const sideReferenceCanvas = $("#sideReferenceCanvas");
export const sideReferenceCtx = sideReferenceCanvas?.getContext("2d");

export const els = {
  statusLine: $("#statusLine"),
  patternMeta: $("#patternMeta"),
  patternList: $("#patternList"),
  customImageInput: $("#customImageInput"),
  customWhiteToggle: $("#customWhiteToggle"),
  patternSizeSlider: $("#patternSizeSlider"),
  patternSizeValue: $("#patternSizeValue"),
  paletteSizePicker: $("#paletteSizePicker"),
  settingsPaletteSizePicker: $("#settingsPaletteSizePicker"),
  customSizeMeta: $("#customSizeMeta"),
  customStats: $("#customStats"),
  patternColorStats: $("#patternColorStats"),
  targetCount: $("#targetCount"),
  controlTitle: $("#controlTitle"),
  toolMeta: $("#toolMeta"),
  stageControls: $("#stageControls"),
  sideReference: $("#sideReference"),
  sideReferenceMeta: $("#sideReferenceMeta"),
  sideReferenceLegend: $("#sideReferenceLegend"),
  studioGrid: $("#studioGrid"),
  workflowProgress: $("#workflowProgress"),
  currentPatternChip: $("#currentPatternChip"),
  currentPatternThumb: document.querySelector("#currentPatternChip .current-pattern-thumb"),
  currentPatternName: $("#currentPatternName"),
  currentPatternMeta: $("#currentPatternMeta"),
  collectionButton: $("#collectionButton"),
  collectionModal: $("#collectionModal"),
  collectionModalClose: $("#collectionModalClose"),
  settingsButton: $("#settingsButton"),
  settingsDot: $("#settingsDot"),
  settingsModal: $("#settingsModal"),
  settingsModalClose: $("#settingsModalClose"),
  shareModal: $("#shareModal"),
  shareModalClose: $("#shareModalClose"),
  remapModal: $("#remapModal"),
  remapModalTitle: $("#remapModalTitle"),
  remapModalBody: $("#remapModalBody"),
  remapModalClose: $("#remapModalClose"),
  remapDoneButton: $("#remapDoneButton"),
  remapResetButton: $("#remapResetButton"),
  toolRack: $("#toolRack"),
  rightPanelTitle: $("#rightPanelTitle"),
  colorPalette: $("#colorPalette"),
  colorMeta: $("#colorMeta"),
  sharePanel: $("#sharePanel"),
  collectionPanel: $("#collectionPanel"),
  collectionCount: $("#collectionCount"),
  bgThemeSelect: $("#bgThemeSelect"),
  topToolStyleSelect: $("#topToolStyleSelect"),
  sandboxButton: $("#sandboxButton"),
  chooseStartButton: $("#chooseStartButton"),
  boardZoomControls: $("#boardZoomControls"),
  zoomOutButton: $("#zoomOutButton"),
  zoomInButton: $("#zoomInButton"),
  zoomResetButton: $("#zoomResetButton"),
  resetButton: $("#resetButton"),
  toast: $("#toast"),
  placeHint: $("#placeHint"),
  achievementToast: $("#achievementToast"),
  stepBadge: $("#stepBadge"),
};
