import { patterns } from './patterns-data.js';

export const state = {
  appMode: "home",
  phase: "choose",
  patternSize: 24,
  customDenoiseLevel: 25,
  paletteSize: 221,
  selectedPattern: patterns[0],
  patternColorMaps: {},
  patternColorMap: {},
  patternEffectiveMapCache: {},
  patternAnalysisCache: {},
  remapFocusSource: null,
  remapModalOpen: false,
  collectionModalOpen: false,
  collectionPageOpen: false,
  settingsModalOpen: false,
  onboardingModalOpen: false,
  shareModalOpen: false,
  gallerySubmitModalOpen: false,
  modalReturnFocus: null,
  sandboxMode: false,
  bgTheme: "mist",
  toolStyle: "candy",
  lampOn: false,
  lampSwitchFlashUntil: 0,
  pressAnim: null, // { startedAt, duration } — scraper sliding bottom→up
  projectedGuideCache: null,
  selectedColor: "K",
  trayColor: null,
  trayProgress: 0,
  trayBeans: 0,
  trayCapacity: 0,
  trayMatrix: [],
  trayPourId: 0,
  spill: null,
  spillDamages: [],
  fusedPieces: [],
  emptyIronEaster: false,
  conceptEaster: false,
  conceptEasterType: null,
  achievements: [],
  floorDrops: [],
  tweezerBead: null,
  needleLoaded: 0,
  placed: [],
  heat: [],
  tool: "needle",
  needleTier: 1,
  lastMoveDir: { x: 1, y: 0 },
  lastCellKey: "",
  errors: [],
  showHints: false,
  pressure: 56,
  temperature: 62,
  ironPos: null,
  cooling: 0,
  flattening: 0,
  warp: 18,
  flipCount: 0,
  craft: "钥匙扣",
  savedCurrent: false,
  lastConversionStats: null,
  pointer: {
    down: false,
    mode: null,
    trayTapPending: false,
    pendingCell: null,
    x: 0,
    y: 0,
    lastX: 0,
    lastY: 0,
    lastT: 0,
  },
  boardView: {
    scale: 1,
    panX: 0,
    panY: 0,
    velX: 0,     // keyboard pan velocity (px/s)
    velY: 0,
    velScale: 0, // keyboard zoom velocity (scale/s)
  },
  kbdNav: {
    up: false, down: false, left: false, right: false,
    zoomIn: false, zoomOut: false,
  },
  gesture: {
    active: false,
    touchActive: false,
    pointers: {},
    startDistance: 0,
    startScale: 1,
    startPanX: 0,
    startPanY: 0,
    startMidX: 0,
    startMidY: 0,
  },
  toolPose: {
    x: 0,
    y: 0,
    visible: false,
  },
  toastTimer: null,
  placeHintTimer: null,
  lastPlaceHintKey: "",
  achievementTimer: null,
  renderDirty: true,
  uiDirty: true,
  previewDirty: true,
  patternsDirty: true,
  pendingWorkflowScroll: true,
  pendingPageReset: false,
  placedVersion: 0,
};
